export * from '../app.component';
export * from './header/header.component';
export * from './footer/footer.component';
export * from './home-page/home-page.component';
export * from './product-page/product-page.component';
export * from './forms/auth-form/auth-form.component';
export * from './forms/x-form/x-form.component';
export * from './information/information.component'
export * from './shopping-cart/shopping-cart.component';
export * from './toast/toast.component';
